### ISSUE TITLE
Project setup issues

### ISSUE THREAD

**Issue by olivierobert** [borbier/nimble-internship#16]
- Prefer using the latest Rails stable version

```
# Bad
gem 'rails', '~> 5.2.4', '>= 5.2.4.1'

# Good

gem 'rails', '6.0.2.1'

```

- Removing unused generated files such as .coffee files

![Screen Shot 2563-02-14 at 15 05 39](https://user-images.githubusercontent.com/696529/74512800-a64dc200-4f3b-11ea-953f-f87c10abed6c.png)

**Comment by borbier** [comment]
I have cleared out Rails version from this [pull Request](https://github.com/borbier/nimble-internship/pull/19)
